site_name: KDY International Sailing School
repo_url: https://github.com/x123/kdy-iss
theme:
  name: material
  features:
    - navigation.footer
    - navigation.expand
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - toc.follow
    #- toc.integrate
  logo: img/kdy-logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
extra:
  generator: false
validation:
  omitted_files: warn
  absolute_links: warn  # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: warn
  anchors: warn  # New in MkDocs 1.6
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - toc:
      permalink: "#"
      baselevel: 2
nav:
  - 'Getting Started': index.md
  - 'Seasons':
    - '2025 Sailing Season': seasons/2025.md
  - 'Skippers':
    - 'Information for Skippers': skipper-info.md
    - 'Pre-Departure Checklist': pre-departure-checklist.md
    - 'Skovshoved Harbour Manoeuvres': skovshoved-manoeuvres.md
    - 'After-Sailing Checklist': after-sailing-checklist.md
    - 'Skipper Approval & Training': skipper-approval-training.md
    - 'Equipment Defects': equipment-defects.md
  - 'Seasons':
    - '2025 Sailing Season': seasons/2025.md
  - 'Safety':
    - 'In Case of Injury': in-case-of-injury.md
    - 'General Safety Information': kdy-safety.md
    - 'VHF Radio': vhf-radio.md
  - 'Harbours':
    - 'Skovshoved Havn':
      - 'Skovshoved Facilities': skovshoved.md
    - 'Rungsted Havn':
      - 'Rungsted Facilities': rungsted.md
  - 'DS37 Manual':
    - 'About the DS37': the-ds37.md
    - 'Safety on the DS37': ds37-safety.md
    - 'Sail Handling': sail-handling.md
    - 'Manoeuvres': manoeuvres.md
    - 'Advanced Topics':
      - 'Match Race Crew Positions': match-race-crew-positions.md
  - 'J/70 Manual':
    - 'About the J/70': the-j70.md
  - 'J80 Manual':
    - 'About the J/80': the-j80.md
  - 'RIB Manual':
    - 'About the RIB': the-rib.md
